import os
import numpy as np
from PIL import Image

# ---------------------------------------------------------------------------
# Module-level singleton — CLIP model is loaded once and reused across calls.
# Loading takes ~2-5s on first call; subsequent calls are fast.
# ---------------------------------------------------------------------------
_clip_model = None
_clip_tokenizer = None
_clip_transform = None
_clip_loaded = False      # True after first load attempt (success or failure)
_clip_load_error = None   # Stores the error message if load failed

# Paths
_BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODELS_DIR = os.path.join(_BASE_DIR, 'models')
PROTOTYPES_PATH = os.path.join(MODELS_DIR, 'clip_prototypes.npz')

# Text prompts used when no trained prototypes are available.
# These allow the analyzer to operate immediately after open_clip is installed,
# before build_clip_prototypes.py is run.
_REAL_TEXTS = [
    "a real photograph taken with a digital camera",
    "an authentic photo with natural photographic imperfections",
    "a genuine photograph with realistic lighting and sensor noise",
]
_AI_TEXTS = [
    "an image generated by artificial intelligence",
    "a synthetic image created by a diffusion model",
    "an AI-generated digital artwork with perfect textures",
]

# Cached text feature tensors (computed once from prompts)
_real_text_features = None
_ai_text_features = None

# Cached prototype centroids (loaded from PROTOTYPES_PATH)
_prototypes = None
_prototypes_loaded = False


def _try_load_clip():
    """
    Attempt to load the CLIP ViT-B/32 model (once).
    Returns True on success, False if open_clip is unavailable.
    """
    global _clip_model, _clip_tokenizer, _clip_transform, _clip_loaded, _clip_load_error
    if _clip_loaded:
        return _clip_load_error is None
    _clip_loaded = True
    try:
        import open_clip
        # ViT-B/32 (openai): smallest good CLIP model, ~350MB first download,
        # cached in ~/.cache/clip after that.
        _clip_model, _, _clip_transform = open_clip.create_model_and_transforms(
            'ViT-B-32', pretrained='openai'
        )
        _clip_model.eval()
        _clip_tokenizer = open_clip.get_tokenizer('ViT-B-32')
        return True
    except Exception as e:
        _clip_load_error = str(e)
        return False


def _get_text_features():
    """
    Compute and cache CLIP text embeddings for the real/AI prompt lists.
    Called lazily on first use.
    """
    global _real_text_features, _ai_text_features
    if _real_text_features is not None:
        return _real_text_features, _ai_text_features

    import torch
    with torch.no_grad():
        real_tokens = _clip_tokenizer(_REAL_TEXTS)
        ai_tokens = _clip_tokenizer(_AI_TEXTS)
        rf = _clip_model.encode_text(real_tokens).float()
        af = _clip_model.encode_text(ai_tokens).float()
        _real_text_features = (rf / rf.norm(dim=-1, keepdim=True)).cpu().numpy()
        _ai_text_features = (af / af.norm(dim=-1, keepdim=True)).cpu().numpy()

    return _real_text_features, _ai_text_features


def _load_prototypes():
    """
    Load CLIP prototype centroids from disk (lazy, cached).
    Returns dict with 'real'/'ai' centroids, or None if file not found.
    Build prototypes by running: python build_clip_prototypes.py
    """
    global _prototypes, _prototypes_loaded
    if _prototypes_loaded:
        return _prototypes
    _prototypes_loaded = True
    if os.path.exists(PROTOTYPES_PATH):
        try:
            data = np.load(PROTOTYPES_PATH)
            _prototypes = {
                'real': data['real_centroid'].astype(np.float64),
                'ai': data['ai_centroid'].astype(np.float64),
                'n_real': int(data.get('n_real', 0)),
                'n_ai': int(data.get('n_ai', 0)),
            }
        except Exception as e:
            _prototypes = None
    return _prototypes


def analyze_clip(image_path: str) -> dict:
    """
    CLIP-based AI image detection via embedding analysis.

    Operates in two modes depending on available resources:

    Mode 1 — Prototype (preferred, higher accuracy):
        Requires: build_clip_prototypes.py to be run at least once.
        Compares the image's CLIP embedding against centroid embeddings of
        real and AI images from your dataset. Score is sigmoid of cosine
        similarity difference. Accuracy improves as dataset grows.

    Mode 2 — Text fallback (works out-of-the-box after pip install):
        No prior training needed. Compares image embedding against CLIP
        text embeddings of "real photograph" vs "AI-generated image" prompts.
        Less accurate than prototype mode but better than random.

    If open_clip is not installed, returns failed=True and is automatically
    excluded from the composite score calculation.

    Returns: {'score': int, 'details': {...}} where score 0=real, 100=AI.
    """
    if not _try_load_clip():
        return {
            'score': 50,
            'failed': True,
            'details': {
                'metrics': {},
                'error': (
                    f'open-clip-torch not available: {_clip_load_error}. '
                    'Install with: pip install open-clip-torch'
                ),
                'mode': 'unavailable',
            },
        }

    try:
        import torch

        img = Image.open(image_path).convert('RGB')
        img_tensor = _clip_transform(img).unsqueeze(0)  # (1, 3, 224, 224)

        with torch.no_grad():
            img_features = _clip_model.encode_image(img_tensor).float()
            img_features = img_features / img_features.norm(dim=-1, keepdim=True)

        img_feat_np = img_features[0].cpu().numpy().astype(np.float64)

        prototypes = _load_prototypes()

        if prototypes is not None:
            # --- Prototype mode ---
            real_c = prototypes['real']
            ai_c = prototypes['ai']

            # Normalize centroids (they may not be unit vectors if averaged raw)
            real_c_norm = real_c / (np.linalg.norm(real_c) + 1e-8)
            ai_c_norm = ai_c / (np.linalg.norm(ai_c) + 1e-8)

            sim_real = float(np.dot(img_feat_np, real_c_norm))
            sim_ai = float(np.dot(img_feat_np, ai_c_norm))

            mode = 'prototype'
            n_samples = prototypes.get('n_real', 0) + prototypes.get('n_ai', 0)
            # Higher scale → steeper sigmoid → more decisive for prototype mode
            scale = 30.0
        else:
            # --- Text fallback mode ---
            real_feats, ai_feats = _get_text_features()

            # Max similarity across all prompts in each class
            sim_real = float(np.max(img_feat_np @ real_feats.T))
            sim_ai = float(np.max(img_feat_np @ ai_feats.T))

            mode = 'text_fallback'
            n_samples = 0
            # Lower scale → softer sigmoid → reflects lower certainty in text mode
            scale = 15.0

        # --- Score: sigmoid of scaled cosine similarity difference ---
        # diff > 0 → image is closer to AI embedding → higher score
        # diff < 0 → image is closer to real embedding → lower score
        diff = float(sim_ai - sim_real)
        score_f = 100.0 / (1.0 + np.exp(-diff * scale))
        final_score = int(round(min(max(score_f, 0), 100)))

        return {
            'score': final_score,
            'details': {
                'metrics': {
                    'sim_to_real': round(sim_real, 4),
                    'sim_to_ai': round(sim_ai, 4),
                    'similarity_diff': round(diff, 4),
                },
                'mode': mode,
                'n_training_samples': n_samples,
            },
        }

    except Exception as e:
        return {
            'score': 50,
            'failed': True,
            'details': {'metrics': {}, 'error': str(e), 'mode': 'error'},
        }
